config/routes.rb
Rails.application.routes.draw do
  root to: "chords#index"
  devise_for :users, controllers: {sessions: 'users/sessions', registrations: 'users/registrations'}
  devise_scope :user do
    get "users/test_sign_in", to: "users/sessions#test_create"
  end
  resources :users, only: :show do
    collection do
      get :search
    end
  end
  resources :songs, except: :index do
    collection do
      get :search
      get :global_search
      get :id_search
    end
  end
  resources :chords, except: :index
  resources :likes, only: [:create, :destroy]
  resources :practices, only: [:create, :destroy]
  resources :messages, only: [:index, :create] do
    collection do
      get :list
    end
  end

  get "informations/apply", to: "informations#apply"
  get "informations/vision", to: "informations#vision"
end

app/models/chord.rb
class Chord < ApplicationRecord
  validates :version, length: {maximum: 50, message: "は50文字以内で設定してください"}
  validates :key, presence: {message: "が空欄です：システムエラー：管理者に連絡してください"}, length: {maximum: 3, message: "は3文字以内で設定してください：システムエラー：管理者に連絡してください"}

  belongs_to :song
  belongs_to :user
  has_many :chordunits, dependent: :destroy
  accepts_nested_attributes_for :chordunits
  has_many :likes, dependent: :destroy
  has_many :practices, dependent: :destroy


end

app/controllers/chords_controller.rb
class ChordsController < ApplicationController
  before_action :set_chord, only: [:show, :edit, :update, :destroy]
  before_action :set_owner, only: [:edit, :update, :destroy]
  before_action :authority_login, except: [:index, :show]
  before_action :authority_user, only: [:edit, :update, :destroy]

  def index
  end

  def show
    @chord = Chord.find(params[:id])
    @chordunits = @chord.chordunits
  end

  def new
    @chord = Chord.new(song_id: params[:song_id])
    @chordunits = []
    $chordunit_num.times do |i|
      @chordunit = @chord.chordunits.build(address: i)
      @chordunits << @chordunit
    end
  end

  def edit
  end

  def create
    @chord = Chord.new(chord_params)
    if @chord.save
      redirect_to @chord, notice: 'コード譜を作成しました'
    else
      @chord.errors.full_messages.each do |message|
        flash.now[:notice] = message
      end
      render :new
    end

  end

  def update
    if @chord.update(chord_params)
      redirect_to @chord, notice: 'コード譜を編集しました'
    else
      render :edit
    end
  end

  def destroy
    @chord.destroy
    redirect_to song_path(@chord.song_id), notice: 'コード譜を削除しました'
  end

  private
    def set_chord
      @chord = Chord.find(params[:id])
    end

    def chord_params
      params.require(:chord).permit(:song_id, :artist_id, :album_id, :version, :key, chordunits_attributes: [:address, :text, :leftbar, :rightbar, :beat, :id, :indicator, :repeat, :part]).merge(user_id: current_user.id)
    end

    def set_owner
      @owner = User.find(@chord.user_id)
    end

end

app/helpers/chords_helper.rb
module ChordsHelper
  def key_of(key)
    "key of #{key}"
  end
end

app/views/chords/edit.html.haml
%aside.l-contents__top
  %section.l-contents__section.c-window__clear.p-chord__section
    .p-chord-new__title.js-judge__edit-chord
      %h2 Edit Chord Score
      .p-chord-new__subtitle -コード譜を編集する-

=form_with url: chord_path, method: :patch, model: @chord, local: true do |f|
  %article.l-contents__main
    %section.c-window__skeleton
      .p-chord-new__song
        .c-song-candidate__wrapper

          .c-song-candidate__lists.c-window__clear-black.u-display__hidden

      .content__search-result
      .p-chord-new__version.c-form__search-box
        .p-chord-new__version--form
          =f.text_field :version, placeholder: "コード譜の名前", class: "c-form__textbox"
        .p-chord-new__version--help.form__textbox
          %a version
    %section.p-chord__wrapper
      .p-chord__key-change
        .c-key-change__wrapper
          .c-key-change__display
            = f.text_field :key, id: "key_name", class: "key-display--form c-key-change__form u-display__hidden", value: "#{@chord.key}"
            .c-key-change__present
              - if ["B","b"].include?(@chord.key[1])
                = key_of(@chord.key[0])
                %a{class: "font_base-key c-font__base"}
                  = @chord.key[1]
              - else
                = key_of(@chord.key)
          =render "/application/key-change"
        .c-key-change__guide << key change!!
        .c-key-change__close-layer
          .c-layer__skeleton
      .p-song__score.c-js__key-change.c-js__disable
        -@chord.chordunits.each_with_index do |chordunit, i|
          =render "/application/chordunit", i: i
        =render "/application/chordunit-form", f: f
    .content__registration
      =f.submit "登録", class:"c-form__btn c-form__btn--registration"
    - breadcrumb :chord_edit
    = render "application/breadcrumbs", layout: "footer"
    .p-chord-new__editor-btn
      >> Editor
=render "/application/chord-editor"

app/views/chords/index.html.haml
%aside.p-top
  %section.c-search.c-window__clear
    .c-search__title コード譜を探す
    =form_with  url: search_songs_path, method: :get, local: true do |f|
      =render "/application/search", f: f
%article
  %section.c-section__sentence-box.p-top__section.u-color__section-red
    %h2.heading Concept
    .sentence
      %p Bluegrassのジャムに参加してみたいけど、
      %ul
        %li コードが分からない…
        %li どの曲を練習すればいいの？
      %p というあなたのためのサービスです。
      .u-space__bottom-10px
      %p=link_to "GrassChordsで描くビジョン", informations_vision_path
  %section.c-section__sentence-box.p-top__section
    %h2.heading How to Use
    .sentence
      %p
        まずは気になる曲名を検索
      %p.p-top__how-to-user
        %p 初心者向け曲をざっと知りたい方は、
        %p Beginner→検索の順にクリック
    %figure
      =image_tag "/images/guitar.png", class: "c-section__image-guitar"

app/views/chords/new.html.haml
%aside.l-contents__top
  %section.l-contents__section.c-window__clear.p-chord__section
    .p-chord-new__title.js-judge__create-chord
      %h2 Create Chord Score
      .p-chord-new__subtitle -コード譜を作成する-

=form_with url: chords_path, method: :post, model: @chord, local: true do |f|
  %article.l-contents__main
    %section.c-window__skeleton
      .p-chord-new__song
        .c-song-candidate__wrapper
          .c-song-candidate__form
            =f.text_field :song_name, autocomplete:"off", id: "search_song_name", placeholder: "曲名",class: "c-form__textbox p-chord-new__textbox c-js__song-candidate"
            =f.text_field :song_id, id: "selected_song_id", class: "u-display__hidden"
          .c-song-candidate__lists.c-window__clear-black.u-display__hidden

      .content__search-result
      .p-chord-new__version.c-form__search-box
        .p-chord-new__version--form
          =f.text_field :version, placeholder: "コード譜の名前", class: "c-form__textbox"
        .p-chord-new__version--help.form__textbox
          %a version
    %section.p-chord__wrapper
      .p-chord__key-change
        .c-key-change__wrapper
          .c-key-change__display
            = f.text_field :key, id: "key_name", class: "key-display--form c-key-change__form u-display__hidden", value: "#{@chord.key}"
            .c-key-change__present
              = key_of(@chord.key)
          =render "/application/key-change"
        .c-key-change__guide << key change!!
        .c-key-change__close-layer
          .c-layer__skeleton
      .p-song__score.c-js__key-change.c-js__disable
        -$chordunit_num.times do |i|
          =render "/application/chordunit", i: i
        =render "/application/chordunit-form", f: f
    .content__registration
      =f.submit "登録", class:"c-form__btn c-form__btn--registration"
    - breadcrumb :chord_new
    = render "application/breadcrumbs", layout: "footer"
    .p-chord-new__editor-btn
      >> Editor
= render "/application/chord-editor"

app/views/chords/show.html.haml
%aside.l-contents__top
  %section.l-contents__section.c-window__clear.p-chord__section
    .p-chord__title
      %h2
        =@chord.song.title
      .p-chord__key
        = "key of "+ @chord.key
    .p-chord__review
      =render "/application/review", chord: @chord
    .p-chord__info
      %p.p-chord__text-version
        =@chord.version + " version"
      %p.p-chord__text-writer
        ="by "+ @chord.user.name
%article.l-contents__main
  -# .p-chord__pdf-btn
  -#   =link_to "PDF Download", url:"#"
  %section.p-chord__wrapper
    .p-chord__key-change
      .c-key-change__wrapper
        .c-key-change__display
          .key-display--form.c-key-change__form.u-display__hidden{value: "#{@chord.key}"}
          .c-key-change__present
            - if ["B","b"].include?(@chord.key[1])
              = key_of(@chord.key[0])
              %a{class: "font_base-key c-font__base"}
                = @chord.key[1]
            - else
              = key_of(@chord.key)
        =render "/application/key-change"
      .c-key-change__guide << key change!!
      .c-key-change__close-layer
        .c-layer__skeleton

    .p-song__score.c-js__key-change.c-js__able
      - @chord.chordunits.each_with_index do |unit, i|
        =render "/application/chordunit", i: i
    .p-chord__manage-score
      =link_to "Edit", edit_chord_path
      %a
        |
      =link_to "Delete", chord_path, method: :delete, data: { confirm: "本当によろしいですか？" }
  -# .p-chord__return
  -#   =link_to "コード譜一覧に戻る", song_path(@chord.song)
  - breadcrumb :chord_show
  = render "application/breadcrumbs", layout: "footer"