config/routes.rb
Rails.application.routes.draw do
  root to: "chords#index"
  devise_for :users, controllers: {sessions: 'users/sessions', registrations: 'users/registrations'}
  devise_scope :user do
    get "users/test_sign_in", to: "users/sessions#test_create"
  end
  resources :users, only: :show do
    collection do
      get :search
    end
  end
  resources :songs, except: :index do
    collection do
      get :search
      get :global_search
      get :id_search
    end
  end
  resources :chords, except: :index
  resources :likes, only: [:create, :destroy]
  resources :practices, only: [:create, :destroy]
  resources :messages, only: [:index, :create] do
    collection do
      get :list
    end
  end

  get "informations/apply", to: "informations#apply"
  get "informations/vision", to: "informations#vision"
end

app/models/user.rb
class User < ApplicationRecord
  # has_secure_password
  attr_accessor :token, :latest_message, :latest_message_date
  validates :name, presence: {message: "が空欄です"}, length: {in: 2..40, message: "は2~40文字に設定してください"}, uniqueness: {case_sensitive: false, message: "は既に登録されています"}
  validates :email, uniqueness: {case_sensitive: false, message: "は既に登録されています"}, length: {in: 3..254, message: "は254文字以内のものを登録してください"}
  validates :place_id, presence: {message: "システムエラー：不正な値が入力されました"}
  validates :admin, exclusion: {in: [true], message: "システムエラー：不正な値が入力されました"}
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :songs
  has_many :chords
  has_many :likes, dependent: :destroy
  has_many :practices, dependent: :destroy
  has_many :practice_songs, dependent: :destroy
  has_many :received_messages, class_name: "Message", foreign_key: "to_user_id"
  has_many :sent_messages, class_name: "Message", foreign_key: "from_user_id"
  has_many :from_users, -> { distinct }, through: :received_messages
  has_many :to_users, -> { distinct }, through: :sent_messages

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :place

  def conversates_with(partner_id)
    self.received_messages.from_(partner_id).or(self.sent_messages.to_(partner_id))
  end

  def self.test_user_find
    self.find(0)
  end

  def update_without_current_password(params, *options)
    params.delete(:current_password)
    if params[:password].blank? && params[:password_confirmation].blank?

      params.delete(:password)
      params.delete(:password_confirmation)
    end

    result = update(params, *options)
    clean_up_passwords

    result
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end
  
  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true
require "uri"
require "net/http"
require "json"
class Users::RegistrationsController < Devise::RegistrationsController
  include UsersHelper
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]
  # before_action :set_owner, only: [:edit, :update, :destroy]
  before_action :authority_login, only:[:edit, :update, :destroy]
  # before_action :authority_user, only: [:edit, :update, :destroy]
  before_action :test_user_protection, only: [:update, :destroy]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  def create
    # [FixMe]
    # error: before access sessions/create action, automatically sign in even if email & password are correct.
    judge_bot_score = 0.5
    json_response = get_recaptcha_response(params[:user][:token])

    if json_response["success"] && json_response["score"] > judge_bot_score

      # 既に登録済みのユーザ情報でエラー発生しないようカラム追加時にデフォルト設定を行った
      # 活動拠点の未登録ユーザがいなくなった時点で下記を削除すること
      params[:user][:place_id] = 0 if params[:user][:place_id] == ""
      @user = User.new(user_params)
      if @user.save
        bypass_sign_in(@user)
        redirect_to root_path, notice: "ようこそ！ アカウントが登録されました"
      else
        render :new
      end

    else
      # [FixMe]
      # by error, user has already signed in
      # if recaptcha authority is failed, i need user sign out.
      @user = User.new
      flash.now[:notice] = "Googleによって、アクセスが中止されました"
      render :new
    end
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  def update
    # 既に登録済みのユーザ情報でエラー発生しないようカラム追加時にデフォルト設定を行った
    # 活動拠点の未登録ユーザがいなくなった時点で下記を削除すること
    params[:user][:place_id] = 0 if params[:user][:place_id] == ""
    # because breadcrumb function needs "params[:id]"
    params[:id] = current_user.id

    if params[:user][:password].present? && params[:user][:password_confirmation].present? && params[:user][:current_password].blank?
      redirect_to edit_user_registration_path(id: current_user.id), notice: "パスワードを変更する際は、現在のパスワードを入力してください" and return
    end

    self.resource = resource_class.to_adapter.get!(send(:"current_#{resource_name}").to_key)
    prev_unconfirmed_email = resource.unconfirmed_email if resource.respond_to?(:unconfirmed_email)

    yield resource if block_given?
    if resource.update_without_current_password(account_update_params)
      set_flash_message_for_update(resource, prev_unconfirmed_email)
      bypass_sign_in resource, scope: resource_name if sign_in_after_change_password?

      respond_with resource, location: after_update_path_for(resource)
    else
      clean_up_passwords resource
      set_minimum_password_length
      respond_with resource
    end

    # #if update_resource(resource, account_update_params)
    # if resource.update_without_current_password(account_update_params)
    #   yield resource if block_given?
    #   if is_flashing_format?
    #     flash_key = update_needs_confirmation?(resource, prev_unconfirmed_email) ?
    #       :update_needs_confirmation : :updated
    #     set_flash_message :notice, flash_key
    #   end
    #   bypass_sign_in(resource_name, resource)
    #   respond_with resource, :location => after_update_path_for(resource)
    # else
    #   clean_up_passwords resource
    #   respond_with resource
    # end
  end

  # DELETE /resource
  def destroy
    # super
    @user.destroy
    redirect_to new_user_registration_path, notice: 'ご利用ありがとうございました。アカウント情報が削除されました'
  end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected
  def user_params
    params.require(:user).permit(:name, :place_id, :email, :password, :password_confirmation).merge(encrypted_password: Devise::Encryptor.digest(User, params[:user][:password]))
  end
  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    root_path(resource)
  end

  def after_update_path_for(resource)
    root_path(resource)
  end

  def test_user_protection
    if current_user.id == 0 || current_user.admin.present?
      redirect_back fallback_location: root_path, notice: 'テストユーザーは編集できません'
    end
  end

  # def update_resource(resource, params)

  #   resource.update_without_current_password(params)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true
require "uri"
require "net/http"
require "json"
class Users::SessionsController < Devise::SessionsController
  include UsersHelper
  before_action :test_user_call, only: [:test_create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  def create
    # error: before access sessions/create action, automatically sign in even if email & password are correct.
    judge_bot_score = 0.5
    json_response = get_recaptcha_response(params[:user][:token])

    if json_response["success"] && json_response["score"] > judge_bot_score
      user = User.find_by(email: params[:user][:email])
      if user && user.valid_password?(params[:user][:password])
        redirect_to root_path, notice: 'ログインしました'
      else
        @user = User.new
        flash.now[:notice] = "メールアドレスもしくはパスワードに誤りがあります"
        render :new
      end
    else
      # by error, user has already signed in
      # if recaptcha authority is failed, i need user sign out.
      sign_out
      @user = User.new
      flash.now[:notice] = "Googleによって、アクセスが中止されました"
      render :new
    end
  end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  def test_create
    sign_in(@user)
    if current_user
      redirect_to root_path, notice: "お試しログインに成功しました"
    else
      redirect_back fallback_location: :new, notice: "お試しログインに失敗しました：システムエラー：管理者に連絡してください"
    end
  end

  protected

  # def session_params
  #   params.permit(:email, :password)
  # end

  def test_user_call
    @user = User.test_user_find
  end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show]

  def show
    @pagy_practice, @practices = pagy(@user.practices.includes(:chord))
    @pagy_like, @likes = pagy(@user.likes.includes(:chord))
  end

  def search
    @users = User.all
    if params[:song_id].present?
      @song = Song.find(params[:song_id])
      @users = @song.users
    end

    if params[:places].present?
      selected_users = []
      @users = @users.where(place_id: params[:places])
    end

    @pagy, @users = pagy(@users)
  end


  private
  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/users_helper.rb
module UsersHelper
  # def ajax_redirect_to(redirect_uri)
  #   { js: "window.location.replace('#{redirect_uri}');" }
  # end

  def get_recaptcha_response(token)
    siteverify_uri = URI.parse("https://www.google.com/recaptcha/api/siteverify?response=#{token}&secret=#{Rails.application.credentials.recaptcha[:recaptcha_secret_key]}")
    response = Net::HTTP.get_response(siteverify_uri)
    json_response = JSON.parse(response.body)
  end
end

app/views/users/search.html.haml
.p-search-result__wrapper
%article.p-search-result__article
  %section.p-search-result__section.c-window__clear
    .c-search__title 練習している曲から探す
    =form_with  url: search_users_path, method: :get, local: true do |f|
      =render "application/search_user", f: f
    %hr{color: "black", size: "1px"}
    .p-search-result__results
      -if @users.present?
        - @users.each do |user|
          =link_to user_path(user) do
            .p-search-result__result.p-search-user__result
              .p-search-user__name
                =user.name
              .u-space__bottom-10px
              .p-user__info-list
                .p-user__info-item 活動拠点：
                .p-user__info-dat
                  - if user.place.present?
                    =user.place.name
                  - else
                    (登録なし)
        = pagy_nav(@pagy).html_safe
      - else
        ユーザーが見つかりませんでした

app/views/users/show.html.haml
%aside.l-contents__top.l-contents__top--low-volume.l-contents__top--sub
  %section.l-contents__section.c-window__clear
    .p-user__title
      %h2 User Information
      .p-user__subtitle -ユーザ情報-
%article.c-user__position-article
  %section.c-section__sentence-box.p-user__section
    .p-user__section-header
      .p-user__icon--user
        %i.fas.fa-user
      .p-user__section-title 基本情報
    .p-user__section-content
      .p-user__info-list
        .p-user__info-item 名前:
        .p-user__info-data
          = @user.name
      - if user_signed_in? && @user.id == current_user.id
        .p-user__info-list
          .p-user__info-item メール:
          .p-user__info-data.p-user__info-data--email
            = @user.email
      .p-user__info-list
        .p-user__info-item 活動拠点:
        .p-user__info-data
          = @user.place.name
    .p-user__section-content
      -if user_signed_in?
        - if current_user.id == @user.id
          =link_to list_messages_path(id: current_user.id), class: "p-user__message-link" do
            .p-user__message.c-form__btn メッセージボックス
        - else
          =link_to messages_path(to_user_id: @user.id), class: "p-user__message-link" do
            .p-user__message.c-form__btn メッセージを送る
      - else
        .p-user__message.p-user__message--no-login.c-form__btn メッセージを送る
        .p-user__message-notice
        ※メッセージの送信にはログインが必要です

    .p-user__section-footer
      .p-user__review_icon.c-review__btn
        .c-review__icon
          %i.fas.fa-heart.p-user__icon-heart
        .c-review__amount
          = @user.chords.sum(:likes_count)
        .c-review__text コード譜の信頼数
      .p-user__edit
        - if user_signed_in? && current_user.id == @user.id
          =link_to "Edit", edit_user_registration_path(id: @user.id)
  %section.c-section__sentence-box.p-user__section
    .p-user__section-header
      .p-user__icon--user
        %i.fas.fa-lightbulb
      .p-user__section-title 練習曲一覧
    .p-user__section-content
      - if @practices.present?
        - @practices.each do |practice|
          .p-user__song{class: "c-js__practice-list--#{practice.id}"}
            .p-user__song-title
              %h2= practice.chord.song.title
            .p-user__song-menu
              = link_to "コード譜を見る", chord_path(practice.chord)
              - if user_signed_in? && current_user.id == @user.id
                %a= "|"
                %a.c-js__practice-delete.u-cursor__pointer{id: practice.chord.id} リストから削除する
        .u-space__top--10px.u-space__bottom--20px= pagy_nav(@pagy_practice).html_safe
      -else
        ="練習曲に登録している楽曲がありません"
  %section.c-section__sentence-box.p-user__section
    .p-user__section-header
      .p-user__icon--user
        %i.fas.fa-heart
      .p-user__section-title 信頼したコード譜
    .p-user__section-content
      - if @likes.present?
        - @likes.each do |like|
          .p-user__song{class: "c-js__like-list--#{like.id}"}
            .p-user__song-header
              .p-user__song-title
                %h2= like.chord.song.title
              .p-user__song-editor
                =link_to ">>作成者を見る", user_path(like.chord.user)
            .p-user__song-menu
              = link_to "コード譜を見る", chord_path(like.chord)
              - if user_signed_in? && current_user.id == @user.id
                %a= "|"
                %a.c-js__like-delete.u-cursor__pointer{id: like.chord.id} 信頼を取り消す
        .u-space__top--10px.u-space__bottom--20px= pagy_nav(@pagy_like).html_safe
      -else
        ="信頼した楽曲がありません"
  - breadcrumb :user_show
  = render "application/breadcrumbs", layout: "footer"