config/routes.rb
Rails.application.routes.draw do
  root to: "chords#index"
  devise_for :users, controllers: {sessions: 'users/sessions', registrations: 'users/registrations'}
  devise_scope :user do
    get "users/test_sign_in", to: "users/sessions#test_create"
  end
  resources :users, only: :show do
    collection do
      get :search
    end
  end
  resources :songs, except: :index do
    collection do
      get :search
      get :global_search
      get :id_search
    end
  end
  resources :chords, except: :index
  resources :likes, only: [:create, :destroy]
  resources :practices, only: [:create, :destroy]
  resources :messages, only: [:index, :create] do
    collection do
      get :list
    end
  end

  get "informations/apply", to: "informations#apply"
  get "informations/vision", to: "informations#vision"
end

app/models/song.rb
class Song < ApplicationRecord
  validates :title, uniqueness: {case_sensitive: false, message: ":%{value}は既に登録されています"}
  validates :title, presence: {message: "が空欄です"}
  validates :title, length: {in: 2..50, message: "は2~50文字に設定してください"}

  has_many :chords, dependent: :destroy
  has_many :practice_songs, dependent: :destroy
  belongs_to :user
  has_many :users, through: :practice_songs



  # 条件にチェックされているときのみand条件で絞り込み
  scope :where_jam, -> (is_jam){where(jam: is_jam) if (is_jam == "true")}
  scope :where_beginner, -> (is_beginner){where(beginner: is_beginner) if (is_beginner == "true")}
  scope :where_standard, -> (is_standard){where(standard: is_standard) if (is_standard == "true")}
  scope :where_vocal, -> (is_vocal){where(vocal: is_vocal) if (is_vocal == "true")}
  scope :where_instrumental, -> (is_instrumental){where(instrumental: is_instrumental) if (is_instrumental == "true")}
  scope :title_search, -> (keyword){where("title like ?", "%#{keyword}%")}

  def self.where_attributes(params)
    self.where_jam(params[:jam]).where_standard(params[:standard]).where_beginner(params[:beginner]).where_jam(params[:jam]).where_instrumental(params[:instrumental])
  end


  def self.search_keywords(keywords)
      keywords.each do |keyword| unless (keywords.nil?)
        title_search(keyword)
      end
  end

  def self.test(kind_of_sort)
      self.order("practice_songs_count desc, title asc")
  end
end

end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :set_song, only: [:show, :edit, :update, :destroy, :id_search]
  before_action :set_owner, only: [:edit, :update, :destroy]
  before_action :authority_login, except: [:index, :show, :search, :global_search]
  before_action :authority_user, only: [:edit, :update, :destroy]

  def index
  end

  def new
    @song = Song.new
  end

  def edit
  end

  def create
    @song = Song.new(song_params)
    if @song.save
      redirect_to @song, notice: '楽曲を登録しました'
    else
      flash.now[:notice] = @song.errors.full_messages
      render :new
    end
  end

  def update
    if @song.update(song_params)
      redirect_to @song, notice: '楽曲を更新しました'
    else
      render :edit
    end
  end

  def destroy
    @song.destroy
    redirect_to root_path, notice: '楽曲を削除しました'
  end

  def show
    @chords = @song.chords.order("likes_count desc")
  end

  def search
    @songs = Song.all.includes(:chords)

    # ソート
    if params[:sort] == "practice"
      @songs = @songs.order("practice_songs_count desc, title asc")
    else
      @songs = @songs.order("title asc")
    end

    search_song
    @count = @songs.length
    @pagy, @songs = pagy(@songs)

    respond_to do |format|
      format.html
      format.json
    end
  end


  def global_search
    @songs = Song.all.includes(:chords)
    @songs = @songs.order("title asc")


    params[:jam] = params[:jam_global]
    params[:standard] = params[:standard_global]
    params[:beginner] = params[:beginner_global]
    params[:vocal] = params[:vocal_global]
    params[:instrumental] = params[:instrumental_global]

    search_song

    @count = @songs.length

    @pagy, @songs = pagy(@songs)

    respond_to do |format|
      format.html{render :search}
      format.json
    end
  end

  def id_search
    # set_songアクションを用いて楽曲レコード取得
  end
  private
    def set_song
      @song = Song.find(params[:id])
    end

    def set_owner
      @owner = User.find(@song.user_id)
    end

    def song_params
      params.require(:song).permit(:title, :jam, :standard, :beginner, :vocal, :instrumental).merge(user_id: current_user.id)
    end

    def search_song
      params[:keyword].strip!
      keywords = params[:keyword].split(/\s+/)

      # 条件検索
      @songs = @songs.where_attributes(params)
      # キーワード検索
      keywords.each do |keyword| unless (params[:keyword].nil?)
        @songs = @songs.title_search(keyword)
      end
    end
  end
end

app/views/songs/edit.html.haml
%aside.l-contents__top.l-contents__top--low-volume.l-contents__top
%article.c-user__position-article
  %section.c-section__sentence-box
    .c-song-new__logo
      %h2 Song Edit
      %a - 楽曲を編集する -
    .c-song-new__form
      =form_with url: song_path, model: @song, method: :patch, local: true do |f|
        .c-form__area
          =f.text_field :title, placeholder:"タイトル", class:"c-form__textbox"
        .c-form__area
          =render "/application/song-attributes", f: f, collection: @song
        .c-form__area
          =f.submit "登録", class:"c-form__btn c-form__btn--login"
    %figure
      =image_tag "/images/banjo.png", class: "c-section__image-banjo"
  - breadcrumb :song_edit
  = render "application/breadcrumbs", layout: "footer"

app/views/songs/new.html.haml
%aside.l-contents__top.l-contents__top--low-volume.l-contents__top
%article.c-user__position-article
  %section.c-section__sentence-box
    .c-song-new__logo
      %h2 Song Registration
      %a - 楽曲を登録する -
    .c-song-new__form
      =form_with url: songs_path, model: @song, method: :post, local: true do |f|
        .c-form__area
          =f.text_field :title, autocomplete:"off", placeholder:"タイトル", class:"c-form__textbox"
        .c-form__area
          =render "/application/song-attributes", f: f
        .c-form__area
          =f.submit "登録", class:"c-form__btn c-form__btn--login"
    %figure
      =image_tag "/images/banjo.png", class: "c-section__image-banjo"
  - breadcrumb :song_new
  = render "application/breadcrumbs", layout: "footer"

app/views/songs/search.html.haml
.p-search-result__wrapper
%article.p-search-result__article
  %section.p-search-result__section.c-window__clear
    .c-search__title コード譜を探す
    =form_with  url: search_songs_path, method: :get, local: true do |f|
      =render "application/search", f: f
      .p-search-result__sort-btns
        =f.label :sort, value: :asc, class: "p-search-result__sort-btn" do
          =f.radio_button :sort, :asc, checked: "checked", class: "c-js__sort u-display__hidden"
          アルファベット 順
        =f.label :sort, value: :practice, class: "p-search-result__sort-btn" do
          =f.radio_button :sort, :practice, checked: ("checked" if params[:sort] == "practice"), class: "c-js__sort u-display__hidden"
          練習してる人数 順
      =f.hidden_field :song_practices
    %hr{color: "black", size: "1px"}
    .p-search-result__counter.c-js__result-counter
      =@count.to_s + " results.."

    .p-search-result__results.c-js_jscroll_selector
      - @songs.each do |song|
        =link_to song_path(song) do
          .p-search-result__result
            .p-search__song-title
              %h2
                =song.title
            .c-icon__attributes
              .c-icon__attribute
                .c-icon__inner--jam.c-js__attribute-state{value: "#{song.jam}"}
                  .c-form__icon-blank
                    %svg{class: "u-position__icon-docked--bottle", width: "19px", height: "22px"}
                      =render "/svg/bottle"
                    %svg{class: "u-position__icon-docked--strawberry", width: "10px", height: "10px"}
                      =render "/svg/strawberry"
              .c-icon__attribute
                %i.fas.fa-users.c-icon__inner--standard.c-js__attribute-state{value: "#{song.standard}"}
              .c-icon__attribute
                %svg{class: "c-icon__inner--beginner c-js__attribute-state", width: "19px", height: "19px", value: "#{song.beginner}"}
                  =render "/svg/beginner"
              .c-icon__attribute
                %i.fas.fa-microphone-alt.c-icon__inner--vocal.c-js__attribute-state{value: "#{song.vocal}"}
              .c-icon__attribute
                %i.fas.fa-guitar.c-icon__inner--instrumental.c-js__attribute-state{value: "#{song.instrumental}"}
            .c-review__btn
              .c-review__icon
                %i.fas.fa-lightbulb.c-review__icon-practice
              .c-review__amount
                =song.practice_songs_count
              .c-review__text 練習してる人の数
      = pagy_nav(@pagy).html_safe

app/views/songs/show.html.haml
%aside.l-contents__top
  %section.p-song__info.l-contents__section.c-window__clear
    .p-song__title
      %h2
        =@song.title
    .p-song__attributes.c-form__attributes
      .p-song__attribute.c-form__attribute
        %p.c-form__icon-blank
          %svg{class: "u-position__icon-docked--bottle", width: "19px", height: "22px"}
            =render "/svg/bottle"
          %svg{class: "u-position__icon-docked--strawberry", width: "10px", height: "10px"}
            =render "/svg/strawberry"
        %a.c-js__attribute-state{value: "#{@song.jam}"} Jam
      .p-song__attribute.c-form__attribute
        %i.fas.fa-users
        %a.c-js__attribute-state{value: "#{@song.standard}"} Standard
      .p-song__attribute.c-form__attribute
        %svg{width: "19px", height: "19px"}
          =render "/svg/beginner"
        %a.c-js__attribute-state{value: "#{@song.beginner}"} Beginner
      .p-song__attribute.c-form__attribute
        %i.fas.fa-microphone-alt
        %a.c-js__attribute-state{value: "#{@song.vocal}"} Vocal
      .p-song__attribute.c-form__attribute
        %i.fas.fa-guitar
        %a.c-js__attribute-state{value: "#{@song.instrumental}"} Instrumental
    .p-chord__manage-score
      =link_to "Edit", edit_song_path
      %a= "|"
      =link_to "Delete", song_path, method: :delete, data: { confirm: "本当によろしいですか？" }
%article.l-contents__main
  - if user_signed_in?
    =link_to new_chord_path(song_id: @song.id), class: "p-song__create_chord" do
      .p-song__create_chord_text コード譜を作成する
  - else
    .p-song__create_chord.p-song__create_chord--no_login コード譜を作成する
    %section.c-window__skeleton.p-song__recommend_login
      =link_to "ログイン後、コード譜の登録が可能です", new_user_session_path
  - if @chords.present?
    - @chords.each_with_index do |chord, i|
      %section.p-song__score-wrapper
        .p-song__header
          .p-song__key
            - if ["B","b"].include?(chord.key[1])
              = "(#{key_of(chord.key[0])}"
              %a{class: "font_base-key c-font__base"}= chord.key[1]
              %a )
            - else
              = "(#{key_of(chord.key)})"
          =link_to ">> 拡大ページ", chord_path(chord), class: "p-song__detail-page"
        .p-song__score{id: "chord_#{i}"}
          - chord.chordunits.each_with_index do |unit, j|
            .c-chordunit__wrapper.c-chordunit__wrapper--small.c-js__cursor-marker
              .c-chordunit__part.c-chordunit__part--small= chord.chordunits[j].part
              .c-chordunit__repeat.c-chordunit__repeat--small= chord.chordunits[j].repeat
              .c-chordunit__indicator.c-chordunit__indicator--small= chord.chordunits[j].indicator
              .c-chordunit.c-chordunit--small{id: "unit_#{i}-#{j}"}
                .c-chordunit__beat.c-chordunit__beat--small= chord.chordunits[j].beat
                .c-chordunit__leftbar.c-chordunit__leftbar--small
                  - unless (chord.chordunits[j-1].rightbar == chord.chordunits[j].leftbar) && (j%8 == 4)
                    =chord.chordunits[j].leftbar
                .c-chordunit__note
                  .c-chordunit__note-name.c-chordunit__note-name--small
                  .c-chordunit__half-note.c-chordunit__half-note--small
                  .c-chordunit__modifier.c-chordunit__modifier--small
                .c-chordunit__rightbar.c-chordunit__rightbar--small= chord.chordunits[j].rightbar
                .c-chordunit__text.u-display__hidden{value: "#{chord.chordunits[j].text}"}= chord.chordunits[j].text
        .p-song__footer
          %p.p-song__text-version= "#{chord.version} version"
          %p.p-song__text-writer= "by #{chord.user.name}"
      .p-song__review
        =render "/application/review", chord: chord, i: i
        %hr
  - else
    %section.c-window__skeleton.p-song__notice この楽曲には、コード譜が登録されていません
  - breadcrumb :song_show
  = render "application/breadcrumbs", layout: "footer"