config/routes.rb
Rails.application.routes.draw do
  root to: "chords#index"
  devise_for :users, controllers: {sessions: 'users/sessions', registrations: 'users/registrations'}
  devise_scope :user do
    get "users/test_sign_in", to: "users/sessions#test_create"
  end
  resources :users, only: :show do
    collection do
      get :search
    end
  end
  resources :songs, except: :index do
    collection do
      get :search
      get :global_search
      get :id_search
    end
  end
  resources :chords, except: :index
  resources :likes, only: [:create, :destroy]
  resources :practices, only: [:create, :destroy]
  resources :messages, only: [:index, :create] do
    collection do
      get :list
    end
  end

  get "informations/apply", to: "informations#apply"
  get "informations/vision", to: "informations#vision"
end

app/views/layouts/_global_search.html.haml
.c-search.p-global-search__wrapper.c-window__skeleton
  %article.p-global-search
    =form_with  url: global_search_songs_path, method: :get, local: true do |f|
      .c-form__search-box
        =f.text_field :keyword, value: (params[:keyword] if params[:keyword]),  class: "c-form__textbox c-form__textbox--search c-js__search-text", placeholder: "曲名で検索"
        =f.label :search, class:"c-search__send-btn c-form__position--box-btn" do
          .c-form__btn
          %i.fas.fa-search.c-form__btn-icon
          =f.submit "", class: "c-form__btn u-color__skeleton-cover"
      .c-search__attribute.c-form__attributes
        =f.label :jam_global, class:"c-form__attribute c-form__box--icon_jam c-js__search-jam c-js__attribute-btn" do
          =f.check_box :jam_global,  {checked: ("checked" if params[:jam] == "true"), class: "c-js__value c-js__value-jam u-display__hidden"}, "true", "false"
          .c-form__icon-blank
          .c-form__inner--icon-jam
            %p.c-form__icon-blank
              %svg{class: "u-position__icon-docked--bottle", width: "19px", height: "22px"}
                =render "/svg/bottle"
              %svg{class: "u-position__icon-docked--strawberry", width: "10px", height: "10px"}
                =render "/svg/strawberry"
          %a.c-search__attribute-text Jam
        =f.label :standard_global, class: "c-form__attribute c-form__box--icon_standard c-js__search-standard c-js__attribute-btn" do
          =f.check_box :standard_global, {checked: ("checked" if params[:standard] == "true"), class: "c-js__value c-js__value-standard u-display__hidden"}, "true", "false"
          .c-form__icon-blank
          %i.fas.fa-users.c-form__inner--icon-standard
          %a.c-search__attribute-text Standard
        =f.label :beginner_global, class: "c-form__attribute c-form__box--icon_beginner c-js__search-beginner c-js__attribute-btn" do
          =f.check_box :beginner_global, {checked: ("checked" if params[:beginner] == "true"), class:"c-js__value c-js__value-beginner u-display__hidden"}, "true", "false"
          .c-form__icon-blank
          .c-form__inner--icon-beginner
            %svg{width: "19px", height: "19px"}
              =render "/svg/beginner"
          %a.c-search__attribute-text Beginner
        =f.label :vocal_global, class: "c-form__attribute c-form__box--icon_vocal c-js__search-vocal c-js__attribute-btn" do
          =f.check_box :vocal_global, {checked: ("checked" if params[:vocal] == "true"), class: "c-js__value c-js__value-vocal u-display__hidden"}, "true", "false"
          .c-form__icon-blank
          %i.fas.fa-microphone-alt.c-form__inner--icon-vocal
          %a.c-search__attribute-text Vocal
        =f.label :instrumental_global, class: "c-form__attribute c-form__box--icon_instrumental c-js__search-instrumental c-js__attribute-btn" do
          =f.check_box :instrumental_global, {checked: ("checked" if params[:instrumental] == "true"), class: "c-js__value c-js__value-instrumental u-display__hidden"}, "true", "false"
          .c-form__icon-blank
          %i.fas.fa-guitar.c-form__inner--icon-instrumental
          %a.c-search__attribute-text Instrumental
  .c-layer__black
    .c-layer__black-sub

app/views/layouts/_navi.html.haml
.p-navi__wrapper
  .p-navi__menu
    - if user_signed_in?
      .p-navi__content.c-js__menu__fade-in
        .p-navi__content__parent.p-navi__btn-pulldown
          .p-navi__link-btn--parent
            .p-navi__icon-box
              %i.fas.fa-user
            %span.p-navi__string__parent
              =link_to "マイページ", user_path(current_user.id)
      .p-navi__content.c-js__menu__fade-in
        .p-navi__content__parent.p-navi__btn-pulldown
          .p-navi__link-btn--parent
            .p-navi__icon-box
              %i.fas.fa-drafting-compass
            %span.p-navi__string__parent データ作成
          .p-navi__icon-box.p-navi__icon-box
            %i.fas.fa-chevron-down
        .ul.p-navi__menu-pulldown
          .li.p-navi__content__child
            %span.p-navi__font__child
              =link_to "楽曲の登録", new_song_path
          .li.p-navi__content__child
            %span.p-navi__font__child
              =link_to "コード譜", new_chord_path
    - else
      .p-navi__content.c-js__menu__fade-in
        .p-navi__content__parent.p-navi__btn-pulldown
          .p-navi__link-btn--parent
            .p-navi__icon-box
              %i.fas.fa-sign-in-alt
            %span.p-navi__string__parent
              =link_to "ログイン", new_user_session_path
      .p-navi__content.c-js__menu__fade-in
        .p-navi__content__parent.p-navi__btn-pulldown
          .p-navi__link-btn--parent
            .p-navi__icon-box
              %i.fas.fa-user-plus
            %span.p-navi__string__parent
              =link_to "ユーザ登録", new_user_registration_path
    -# .p-navi__content.c-js__menu__fade-in
    -#   .p-navi__content__parent
    -#     .p-navi__link-btn--parent
    -#       .p-navi__icon-box
    -#         %i.far.fa-file-pdf
    -#       %span.p-navi__string__parent コード表 作成
    .p-navi__content.c-js__menu__fade-in
      .p-navi__content__parent.p-navi__btn-pulldown
        .p-navi__link-btn--parent
          .p-navi__icon-box
            %i.far.fa-address-book
          %span.p-navi__string__parent
            =link_to "ユーザ検索", search_users_path
    - if user_signed_in?
      .p-navi__content.c-js__menu__fade-in
        .p-navi__content__parent
          .p-navi__link-btn--parent
            .p-navi__icon-box
              %i.fas.fa-sign-out-alt
            %span.p-navi__string__parent
              =link_to "ログアウト", destroy_user_session_path, method: :delete

  .c-layer__black
    .c-layer__black-sub

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1"}
    %link{href: "https://fonts.googleapis.com/css2?family=M+PLUS+1p:wght@400;500&family=Nunito:wght@400;700&family=Rum+Raisin&family=Volkhov&display=swap", rel: "stylesheet"}
    %title Grass Chords - Bluegrassジャムセッション 支援サービス
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', type: 'text/css'
    = javascript_include_tag 'application'
    = favicon_link_tag()
  %body
    =csrf_meta_tag
    %header.l-header
      %h1
        =link_to "Grass Chords", root_path, class:"l-header__logo"
      .l-header__menu
        .l-header__search-btn
          %i.fas.fa-search.l-search_btn
        .l-header__opn-box.u-header__margin.c-js__menu-cls
          %span
          %span
          %span

    %p.l-header__error= flash[:error]
    %p.l-header__alert= flash[:alert]
    %p.l-header__notice= flash[:notice]

    .l-contents
      %main.l-main
        =yield
      %navi.l-navi.c-js__navi__fade-in
        =render "/layouts/navi"
      %navi.l-contents__global-search.c-js__search__fade-in
        =render "/layouts/global_search"
    %footer.l-footer
      %h1.u-size__footer-copyright ©2020 Grass Chords
      %h1.u-size__footer-name by Shota Imoto